---
name: Deploy Documentation
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    paths:
      - 'docs/**'
      - mkdocs.yml
    branches:
      - main
jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Configure Git User
      # Required by mike for the commit it does to the gh-pages branch
        run: |
          git config user.name "ci-docs"
          git config user.email "ci-docs@dummy.com"
      - name: Deploy the latest documents from new release
        if: ${{ github.event_name == 'release' }}
        run: mike deploy --push --update-aliases "${GITHUB_REF#refs/*/}" latest
      - name: Deploy the development docs
        if: ${{ github.event_name != 'release' }}
        run: mike deploy --push unreleased
